### ISSUE TITLE
Understanding multiple origin ASNs

### ISSUE THREAD

**Issue by bswinnerton** [bgpkit/bgpkit-parser#121]
Hi there,

I'm using the bgpkit-parser to pull down a [full mrt dump](https://data.ris.ripe.net/rrc25/latest-bview.gz) from RIPE's RIS project. When parsing the file using bgpkit-parser I see that I can iterate over a set of `BgpElem`'s, each of which have an attribute called `origin_asns`. I'm trying to understand situations in which there would be more than one origin ASN. Intuitively I would think the origin ASN is just the last ASN in the AS_PATH.

Conceptually I've been thinking about this mrt dump as the route collector's RIB and a `BgpElem` as effectively one route in the RIB. With that framing, I can imagine having multiple `BgpElem`'s that have the same prefix but with multiple origin AS conficts, but I wouldn't expect to see those in a _single_ `BgpElem`. I suspect my mental model is wrong here, or perhaps this has something to do with BGP aggregation, and was hoping you could help clarify 🙏.

**Comment by digizeph** [comment]
Hey Brooks,

The `origin_asns` is a utility short-cut for quickly getting the AS numbers out. The main issue you mentioned is by the design according to the BGP protocol RFC.

### `AsPath` definition

The `AsPath` struct are not defined as simply a vector of numbers. They are in fact define as a vector of `AsPathSegment`
https://github.com/bgpkit/bgpkit-parser/blob/04c27c459e13a9a59c2a0f1f7efb9a06f2540aa5/src/models/bgp/attributes/aspath.rs#L25-L28

while each `AsPathSegment` is defined as a enum of four types:

https://github.com/bgpkit/bgpkit-parser/blob/04c27c459e13a9a59c2a0f1f7efb9a06f2540aa5/src/models/bgp/attributes/aspath.rs#L8-L13


In most cases, you would see a `AsPath` with a single `AsPathSegment` value of `AsSequence` type, which is essentially what you would expect: a vector of AS numbers.



See [RFC4271 BGP Update format section](https://www.rfc-editor.org/rfc/rfc4271#section-4.3) for more details. (Also [RFC5065](https://datatracker.ietf.org/doc/html/rfc5065) for AS Confederations if you're interested in other two enum types.)
<img width="543" alt="image" src="https://github.com/bgpkit/bgpkit-parser/assets/659667/f5a1544f-38aa-417b-a03f-b41e63995ef3">

However, in rare cases, you would see `AsPath` with `AsPathSegment` of type `AsSet` or `ConfedAsSet`. In these cases, the last hop could be a set of ASNs, and thus making all of them the origins.

### `origin_asns` calculation

The `origin_asns` is calculated using the `AsPath`'s `get_origins()` function:
https://github.com/bgpkit/bgpkit-parser/blob/04c27c459e13a9a59c2a0f1f7efb9a06f2540aa5/src/models/bgp/attributes/aspath.rs#L104-L114
As you can see from the code, it simply grabs the last `AsPathSegment`, and if it's a `AsSequence`, then it gets the last AS number out, otherwise it clones the whole `AsSet`.


### Personal recommendation

Nowadays, I would completely discard any BGP messages with AS_Set. In your particular case, if I see `origin_asns` has more than one number, I would just discard the whole `BgpElem`.

Another way to get the origin is to call the `.to_u32_vec()` function on a given `AsPath`
On the bleed-edge version `0.10.0-alpha.1`, I added another utiltity function to `BgpElem` called `.get_as_path_opt()` which returns a `Option<Vec<u32>>` when called. If the message is a withdrawal, or the AS path contains non-as-sequence segment, it will return a `None`. You can safely get the last element of the return u32 vector and treat it as the origin if you'd like.

https://github.com/bgpkit/bgpkit-parser/blob/04c27c459e13a9a59c2a0f1f7efb9a06f2540aa5/src/models/bgp/elem.rs#L188-L193


I hope this makes sense, and I am open to ideas on making this mess clearer to users.

**Comment by bswinnerton** [comment]
Thank you for the informative and thoughtful response, Mingwei!

> I hope this makes sense, and I am open to ideas on making this mess clearer to users.

This all makes perfect sense, thank you for the pointers to the spec. 

I was looking at `.get_as_path_opt()` yesterday evening, and I think that will be quite helpful for my use case on the next version, but until then your suggestion around discarding the `BgpElem` will work well for my use case.
